name: Test Release
runs:
  using: composite
  steps:
    - name: Start Vault
      shell: bash
      run: |
        echo "Kill Vault"
        pkill vault && echo "Vault killed" || echo "No Vault process was running"

        echo "Install Vault"
        ./src/test/bash/create_certificates.sh
        ./src/test/bash/install_vault.sh

        echo "Run Vault"
        ./src/test/bash/local_run_vault.sh &
        echo "Vault Running"

    - name: Test Release
      shell: bash
      run: ./mvnw --batch-mode --settings release-train-settings.xml clean verify --activate-profiles releaseTrain -Xms256M -Xmx1024M -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 -Dhttps.protocols=TLSv1.2

    - name: Stop Vault
      if: always()
      shell: bash
      run: pkill vault && echo "Vault killed" || echo "No Vault process was running"