
include::intro.adoc[]

== Features

=== Spring Cloud Vault Config Client

Specifically for Spring applications:

* Retrieve secrets from Vault and initialize Spring `Environment` with remote property sources
* Obtain secrets secured with SSL
* Generate credentials for MySQL, PostgreSQL, Apache Cassandra, MongoDB, Consul, AWS, and RabbitMQ.
* https://www.vaultproject.io/docs/auth/token.html[Token], https://www.vaultproject.io/docs/auth/app-id.html[AppId] authentication,
and https://www.vaultproject.io/docs/auth/aws-ec2.html[AWS-EC2] authentication
* Bootstrap application context: a parent context for the main application that can be trained to do anything

== Quick Start

include::quickstart.adoc[]

== Building

==== Build requirements for Vault

Spring Cloud Vault Config requires SSL certificates and a running
Vault instance listening on `localhost:8200`. Certificates and the Vault
setup are scripted, the scripts are located in `src/test/bash`.

The following scripts need to be run prior to building the project for the tests to pass.

    $ ./src/test/bash/install_vault.sh
    $ ./src/test/bash/create_certificates.sh
    $ ./src/test/bash/local_run_vault.sh

Changes to the documentation should be made to the adocs found under `docs/src/main/asciidoc/`

README.adoc can be re-generated via the following

    $ ./docs/src/main/ruby/generate_readme.sh > README.adoc

This script requires ruby and the asciidoctor gem installed (`gem install asciidoctor`)

include::https://raw.githubusercontent.com/spring-cloud/spring-cloud-build/master/docs/src/main/asciidoc/building.adoc[]

== Contributing

include::https://raw.githubusercontent.com/spring-cloud/spring-cloud-build/master/docs/src/main/asciidoc/contributing.adoc[]