
include::intro.adoc[]

== Features

=== Spring Cloud Vault Config Client

Specifically for Spring applications:

* Retrieve secrets from Vault and initialize Spring Environment with remote property sources
* Obtain http://cloud.spring.io/spring-cloud-vault-config/spring-cloud-vault-config.html#vault.config.backends.generic[secrets] secured with SSL
* Generate credentials for
http://cloud.spring.io/spring-cloud-vault-config/spring-cloud-vault-config.html#vault.config.backends.mysql[MySQL],
http://cloud.spring.io/spring-cloud-vault-config/spring-cloud-vault-config.html#vault.config.backends.postgresql[PostgreSQL],
http://cloud.spring.io/spring-cloud-vault-config/spring-cloud-vault-config.html#vault.config.backends.cassandra[Apache Cassandra],
http://cloud.spring.io/spring-cloud-vault-config/spring-cloud-vault-config.html#vault.config.backends.mongodb[MongoDB],
http://cloud.spring.io/spring-cloud-vault-config/spring-cloud-vault-config.html#vault.config.backends.consul[Consul],
http://cloud.spring.io/spring-cloud-vault-config/spring-cloud-vault-config.html#vault.config.backends.aws[AWS], and http://cloud.spring.io/spring-cloud-vault-config/spring-cloud-vault-config.html#vault.config.backends.rabbitmq[RabbitMQ].
* http://cloud.spring.io/spring-cloud-vault-config/spring-cloud-vault-config.html#vault.config.authentication.token[Token],
http://cloud.spring.io/spring-cloud-vault-config/spring-cloud-vault-config.html#vault.config.authentication.appid[AppId],
http://cloud.spring.io/spring-cloud-vault-config/spring-cloud-vault-config.html#vault.config.authentication.approle[AppRole],
http://cloud.spring.io/spring-cloud-vault-config/spring-cloud-vault-config.html#vault.config.authentication.clientcert[Client Certificate],
http://cloud.spring.io/spring-cloud-vault-config/spring-cloud-vault-config.html#vault.config.authentication.cubbyhole[Cubbyhole], and
http://cloud.spring.io/spring-cloud-vault-config/spring-cloud-vault-config.html#vault.config.authentication.awsec2[AWS-EC2] authentication
* Bootstrap application context: a parent context for the main application that can be trained to do anything


== Quick Start

include::quickstart.adoc[]

== Building

==== Build requirements for Vault

Spring Cloud Vault Config requires SSL certificates and a running
Vault instance listening on `localhost:8200`. Certificates and the Vault
setup are scripted, the scripts are located in `src/test/bash`.

The following scripts need to be run prior to building the project for the tests to pass.

    $ ./src/test/bash/install_vault.sh
    $ ./src/test/bash/create_certificates.sh
    $ ./src/test/bash/local_run_vault.sh

Changes to the documentation should be made to the adocs found under `docs/src/main/asciidoc/`

README.adoc can be re-generated via the following

    $ ./docs/src/main/ruby/generate_readme.sh > README.adoc

This script requires ruby and the asciidoctor gem installed (`gem install asciidoctor`)

include::https://raw.githubusercontent.com/spring-cloud/spring-cloud-build/master/docs/src/main/asciidoc/building.adoc[]

== Contributing

include::https://raw.githubusercontent.com/spring-cloud/spring-cloud-build/master/docs/src/main/asciidoc/contributing.adoc[]
