:backends: https://docs.spring.io/spring-cloud-vault/reference/secret-backends.html
:auth: https://docs.spring.io/spring-cloud-vault/reference/authentication.html

[[features]]
= Features

[[spring-cloud-vault-config-client]]
== Spring Cloud Vault Config Client

Specifically for Spring applications:

* Retrieve secrets from Vault and initialize Spring Environment with remote property sources.
* Obtain {backends}#vault.config.backends.kv[Key-Value secrets] secured with SSL.
* Generate credentials for
{backends}#vault.config.backends.mysql[MySQL],
{backends}#vault.config.backends.postgresql[PostgreSQL],
{backends}#vault.config.backends.cassandra[Apache Cassandra],
{backends}#vault.config.backends.mongodb[MongoDB],
{backends}#vault.config.backends.consul[Consul],
{backends}#vault.config.backends.aws[AWS], and {backends}#vault.config.backends.rabbitmq[RabbitMQ].
* {auth}#vault.config.authentication.token[Token],
{auth}#vault.config.authentication.appid[AppId],
{auth}#vault.config.authentication.approle[AppRole],
{auth}#vault.config.authentication.clientcert[Client Certificate],
{auth}#vault.config.authentication.cubbyhole[Cubbyhole],
{auth}#vault.config.authentication.awsec2[AWS-EC2] authentication,
{auth}#vault.config.authentication.awsiam[AWS-IAM] authentication, and
{auth}#vault.config.authentication.kubernetes[Kubernetes] authentication.

* Bootstrap application context: a parent context for the main application that can be trained to do anything.

include::../../../modules/ROOT/pages/quickstart.adoc[]

[[building]]
= Building

[[build-requirements-for-vault]]
== Build requirements for Vault

Spring Cloud Vault Config requires SSL certificates and a running Vault instance listening on `localhost:8200`.
Certificates and the Vault setup are scripted, the scripts are located in `src/test/bash`.

The following scripts need to be run prior to building the project for the tests to pass.

[source,bash]
----
$ ./src/test/bash/install_vault.sh
$ ./src/test/bash/create_certificates.sh
$ ./src/test/bash/local_run_vault.sh
----

Leave Vault uninitialized, the tests will initialize and unseal Vault.
They will also create a root token `00000000-0000-0000-0000-000000000000`.

Changes to the documentation should be made to the adocs found under `docs/src/main/asciidoc/`

`README.adoc` can be re-generated via the following

[source,bash]
----
$ ./docs/src/main/ruby/generate_readme.sh > README.adoc
----

This script requires ruby and the asciidoctor gem installed (`gem install asciidoctor`)

include::https://raw.githubusercontent.com/spring-cloud/spring-cloud-build/main/docs/modules/ROOT/pages/building.adoc[]

[[contributing]]
= Contributing

include::https://raw.githubusercontent.com/spring-cloud/spring-cloud-build/master/docs/src/main/asciidoc/contributing.adoc[]
