:docs: https://cloud.spring.io/spring-cloud-vault/spring-cloud-vault.html

[[features]]
= Features

[[spring-cloud-vault-config-client]]
== Spring Cloud Vault Config Client

Specifically for Spring applications:

// TODO: fix links
* Retrieve secrets from Vault and initialize Spring Environment with remote property sources.
* Obtain {docs}#vault.config.backends.kv[Key-Value secrets] secured with SSL.
* Generate credentials for
{docs}#vault.config.backends.mysql[MySQL],
{docs}#vault.config.backends.postgresql[PostgreSQL],
{docs}#vault.config.backends.cassandra[Apache Cassandra],
{docs}#vault.config.backends.mongodb[MongoDB],
{docs}#vault.config.backends.consul[Consul],
{docs}#vault.config.backends.aws[AWS], and {docs}#vault.config.backends.rabbitmq[RabbitMQ].
* {docs}#vault.config.authentication.token[Token],
{docs}#vault.config.authentication.appid[AppId],
{docs}#vault.config.authentication.approle[AppRole],
{docs}#vault.config.authentication.clientcert[Client Certificate],
{docs}#vault.config.authentication.cubbyhole[Cubbyhole],
{docs}#vault.config.authentication.awsec2[AWS-EC2] authentication,
{docs}#vault.config.authentication.awsiam[AWS-IAM] authentication, and
{docs}#vault.config.authentication.kubernetes[Kubernetes] authentication.

* Bootstrap application context: a parent context for the main application that can be trained to do anything.

include::../../../modules/ROOT/pages/quickstart.adoc[]

[[building]]
= Building

[[build-requirements-for-vault]]
== Build requirements for Vault

Docker is the only prerequisite for building Spring Cloud Vault.
The tests start Vault themselves using https://testcontainers.com[Testcontainers], so no Vault installation is required and nothing needs to be listening on `localhost:8200`.

[source,bash]
----
$ ./mvnw clean install
----

The build generates the SSL certificates the tests need (`work/ca`, `work/keystore.jks` and `work/client-cert.jks`) by running `src/test/bash/create_certificates.sh` from the reactor root, so `openssl` and `keytool` need to be on the `PATH`.
The tests initialize and unseal the Vault container and create a root token `00000000-0000-0000-0000-000000000000`.

Changes to the documentation should be made to the adocs found under `docs/src/main/asciidoc/`

`README.adoc` can be re-generated via the following

[source,bash]
----
$ ./docs/src/main/ruby/generate_readme.sh > README.adoc
----

This script requires ruby and the asciidoctor gem installed (`gem install asciidoctor`)

include::https://raw.githubusercontent.com/spring-cloud/spring-cloud-build/main/docs/modules/ROOT/pages/building.adoc[]

[[contributing]]
= Contributing

include::https://raw.githubusercontent.com/spring-cloud/spring-cloud-build/master/docs/src/main/asciidoc/contributing.adoc[]
