= Spring Cloud Vault
:github: https://github.com/spring-cloud-incubator/spring-cloud-vault-config
:githubmaster: {github}/tree/master
:docslink: {githubmaster}/docs/src/main/asciidoc
:toc:

include::intro.adoc[]

== Quick Start

include::quickstart.adoc[]

== Authentication methods

Different organizations have different requirements for security
and authentication. Vault reflects that need by shipping multiple authentication
methods. Spring Cloud Vault supports token and AppId authentication.

=== Token authentication

Tokens are the core method for authentication within Vault.
Token authentication requires a static token to be provided using the
https://github.com/spring-cloud/spring-cloud-commons/blob/master/docs/src/main/asciidoc/spring-cloud-commons.adoc#the-bootstrap-application-context[Bootstrap Application Context].


.bootstrap.yml
----
spring.cloud.vault:
    enabled: true
    token: 00000000-0000-0000-0000-000000000000
----

See also: https://www.vaultproject.io/docs/concepts/tokens.html[Vault Documentation: Tokens]

=== AppId authentication

Vault supports https://www.vaultproject.io/docs/auth/app-id.html[AppId]
authentication that consists of two hard to guess tokens. The AppId
defaults to `spring.application.name` that is statically configured.
The second token is the UserId which is a part determined by the application,
usually related to the runtime environment. IP address, Mac address or a
Docker container name are good examples. Spring Cloud Vault Config supports
IP address, Mac address and static UserId's (e.g. supplied via System properties).
The IP and Mac address are represented as Hex-encoded SHA256 hash.

IP address-based UserId's use the local host's IP address.

[source,yaml]
.bootstrap.yml using SHA256 IP-Address UserId's
----
spring.cloud.vault:
    enabled: true
    authentication: APPID
    app-id:
        user-id: IP_ADDRESS
----

The corresponding command to generate the IP address UserId from a command line is:

----
$ echo -n 192.168.99.1 | sha256sum
----
NOTE: Including the line break of `echo` leads to a different hash value
so make sure to include the `-n` flag.

Mac address-based UserId's obtain their network device from the
localhost-bound device. The configuration also allows specifying
a `network-interface` hint to pick the right device. The value of
`network-interface` is optional and can be either an interface
name or interface index (0-based).

[source,yaml]
.bootstrap.yml using SHA256 Mac-Address UserId's
----
spring.cloud.vault:
    enabled: true
    authentication: APPID
    app-id:
        user-id: MAC_ADDRESS
        network-interface: eth0
----

The corresponding command to generate the IP address UserId from a command line is:

----
$ echo -n 0AFEDE1234AC | sha256sum
----

NOTE: The Mac address is specified uppercase and without colons.
Including the line break of `echo` leads to a different hash value
so make sure to include the `-n` flag.

==== Custom UserId

The UserId generation is an open mechanism. You can set `spring.cloud.vault.app-id.user-id`
to any string and the configured value will be used as static UserId.

A more advanced approach lets you set `spring.cloud.vault.app-id.user-id` to a
classname. This class must be on your classpath and must implement
the `org.springframework.cloud.vault.AppIdUserIdMechanism` interface
and the `createUserId` method. Spring Cloud Vault will obtain the UserId
by calling `createUserId` each time it authenticates using AppId to
obtain a token.

[source,yaml]
.bootstrap.yml
----
spring.cloud.vault:
    enabled: true
    authentication: APPID
    app-id:
        user-id: com.examlple.MyUserIdMechanism
----

[source,yaml]
.MyUserIdMechanism.java
----
public class MyUserIdMechanism implements AppIdUserIdMechanism {

  @Override
  public String createUserId() {
    String userId = ...
    return userId;
  }
}
----

=== AWS-EC2 authentication

The https://www.vaultproject.io/docs/auth/aws-ec2.html[aws-ec2]
auth backend provides a secure introduction mechanism
for AWS EC2 instances, allowing automated retrieval of a Vault
token. Unlike most Vault authentication backends, this backend
does not require first-deploying, or provisioning security-sensitive
credentials (tokens, username/password, client certificates, etc).
Instead, it treats AWS as a Trusted Third Party and uses the
cryptographically signed dynamic metadata information that uniquely
represents each EC2 instance.

[source,yaml]
.bootstrap.yml using AWS-EC2 Authentication
----
spring.cloud.vault:
    enabled: true
    authentication: AWS_EC2
----

AWS-EC2 authentication enables nonce by default to follow
the Trust On First Use (TOFU) principle. Any unintended party that
gains access to the PKCS#7 signed identity metadata can authenticate
against Vault.

During the first login, Spring Cloud Vault generates a nonce
that is stored in the auth backend aside the instance Id.
Re-authentication requires the same nonce to be sent. Any other
party does not have the nonce and can raise an alert in Vault for
further investigation.

The nonce is kept in memory and is lost during application restart.

[source,yaml]
.bootstrap.yml with disabled nonce
----
spring.cloud.vault:
    enabled: true
    authentication: AWS_EC2
    aws-ec2:
        use-nonce: false
----

AWS-EC2 authentication roles are optional and default to the AMI.
You can configure the authentication role by setting the
`spring.cloud.vault.aws-ec2.role` property.

[source,yaml]
.bootstrap.yml with configured role
----
spring.cloud.vault:
    enabled: true
    authentication: AWS_EC2
    aws-ec2:
        role: application-server
----

== Backends

[[vault-client-generic]]
=== Generic Backend

Spring Cloud Vault supports at the basic level the generic secret backend.
The generic secret backend allows storage of arbitrary values as key-value
store. A single context can store one or many key-value tuples.
Contexts can be organized hierarchically and so Spring Cloud Vault
allows using the Application name set in `spring.application.name`
and a default context name (`application`) in combination with active profiles.

----
/secret/{application}/{profile}
/secret/{application}
/secret/{defaultContext}/{profile}
/secret/{defaultContext}
----

Spring Cloud Vault adds all active profiles to the list of possible context paths.
No active profiles will skip accessing contexts with a profile name.

[source,yaml]
----
spring.cloud.vault:
    enabled: true
    ...
    generic:
        enabled: true
        default-context: application
----

See also: https://www.vaultproject.io/docs/secrets/generic/index.html[Vault Documentation: Using the generic secret backend]

[[vault-client-consul]]
=== Consul

Spring Cloud Vault allows to obtain credentials for Hashicorp Consul.
The integration can be enabled by setting `spring.cloud.vault.consul.enabled=true`
(default `false`). The obtained token is stored in `spring.cloud.consul.token`
so using Spring Cloud Consul can pick up the generated
credentials without further configuration. You can configure the property name
by setting `spring.cloud.vault.consul.token-property`.

[source,yaml]
----
spring.cloud.vault:
    enabled: true
    ...
    consul:
        enabled: true
----

See also: https://www.vaultproject.io/docs/secrets/consul/index.html[Vault Documentation: Setting up Consul with Vault]

[[vault-client-rabbitmq]]
=== RabbitMQ

Spring Cloud Vault allows to obtain credentials for RabbitMQ.
The integration can be enabled by setting `spring.cloud.vault.rabbit.enabled=true`
(default `false`). Username and password are stored in `spring.rabbit.username`
and `spring.rabbit.password` so using Spring Boot will pick up the generated
credentials without further configuration. You can configure the property names
by setting `spring.cloud.vault.rabbit.username-property` and
`spring.cloud.vault.rabbit.password-property`.

[source,yaml]
----
spring.cloud.vault:
    enabled: true
    ...
    rabbit:
        enabled: true
----

See also: https://www.vaultproject.io/docs/secrets/rabbit/index.html[Vault Documentation: Setting up RabbitMQ with Vault]

[[vault-client-database-backends]]
== Database backends

Vault supports several database secret backends to generate database
credentials dynamically based on configured roles. This means,
services that need to access a database no longer need to configure
credentials: they can request them from Vault, and use Vault's leasing
mechanism to more easily roll keys.

Spring Cloud Vault integrates with these backends:

* <<vault-client-database-cassandra>>
* <<vault-client-database-mysql>>
* <<vault-client-database-postgresql>>

Using a database secret backend requires to enable the backend in the configuration.

NOTE: Enabling multiple JDBC-compliant databases will generate credentials
and store them by default in the same property keys hence property names for
JDBC secrets need to be configured separately.

[[vault-client-database-cassandra]]
=== Apache Cassandra

Spring Cloud Vault allows to obtain credentials for Apache Cassandra.
The integration can be enabled by setting `spring.cloud.vault.cassandra.enabled=true`
(default `false`). Username and password are stored in `spring.data.cassandra.username`
and `spring.data.cassandra.password` so using Spring Boot will pick up the generated
credentials without further configuration. You can configure the property names
by setting `spring.cloud.vault.cassandra.username-property` and
`spring.cloud.vault.cassandra.password-property`.

[source,yaml]
----
spring.cloud.vault:
    enabled: true
    ...
    cassandra:
        enabled: true
----

See also: https://www.vaultproject.io/docs/secrets/cassandra/index.html[Vault Documentation: Setting up Apache Cassandra with Vault]

[[vault-client-database-mysql]]
=== MySQL

Spring Cloud Vault allows to obtain credentials for MySQL.
The integration can be enabled by setting `spring.cloud.vault.mysql.enabled=true`
(default `false`). Username and password are stored in `spring.datasource.username`
and `spring.datasource.password` so using Spring Boot will pick up the generated
credentials without further configuration. You can configure the property names
by setting `spring.cloud.vault.mysql.username-property` and
`spring.cloud.vault.mysql.password-property`.

[source,yaml]
----
spring.cloud.vault:
    enabled: true
    ...
    mysql:
        enabled: true
----

See also: https://www.vaultproject.io/docs/secrets/mysql/index.html[Vault Documentation: Setting up MySQL with Vault]

[[vault-client-database-postgresql]]
=== PostgreSQL

Spring Cloud Vault allows to obtain credentials for PostgreSQL.
The integration can be enabled by setting `spring.cloud.vault.postgresql.enabled=true`
(default `false`). Username and password are stored in `spring.datasource.username`
and `spring.datasource.password` so using Spring Boot will pick up the generated
credentials without further configuration. You can configure the property names
by setting `spring.cloud.vault.postgresql.username-property` and
`spring.cloud.vault.postgresql.password-property`.

[source,yaml]
----
spring.cloud.vault:
    enabled: true
    ...
    postgresql:
        enabled: true
----

See also: https://www.vaultproject.io/docs/secrets/postgresql/index.html[Vault Documentation: Setting up PostgreSQL with Vault]


[[vault-client-fail-fast]]
== Vault Client Fail Fast

In some cases, it may be desirable to fail startup of a service if
it cannot connect to the Vault Server.  If this is the desired
behavior, set the bootstrap configuration property
`spring.cloud.vault.failFast=true` and the client will halt with
an Exception.

[[vault-client-ssl]]
== Vault Client SSL configuration

SSL can be configured declaratively by setting various properties.
You can set either `javax.net.ssl.trustStore` to configure
JVM-wide SSL settings or `spring.cloud.vault.ssl.trust-store`
to set SSL settings only for Spring Cloud Vault Config.

[source,yaml]
----
spring.cloud.vault:
    ssl:
        trust-store: classpath:keystore.jks
        trust-store-password: changeit
----

Please note that configuring `spring.cloud.vault.ssl.*` can be only
applied when either Apache Http Components, netty or the OkHttp client
is on your class-path.

